# Generated by Django 6.0.2 on 2026-03-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='booking_pay_user_id_1d5284_idx',
            old_name='booking_paym_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='booking_pay_transac_39578e_idx',
            old_name='booking_paym_transac_status_idx',
        ),
    ]
