# Generated by Django 6.0.2 on 2026-03-12 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_payment_payment_proof_tournament_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='sponsor_logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='advertise_duration',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='company_details',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='promotion_type',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('HOME_TOP', 'Home - Top'), ('HOME_BOTTOM', 'Home - Bottom'), ('TOURNAMENT_PAGE', 'Tournament Page'), ('SIDEBAR', 'Sidebar')], default='HOME_TOP', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournamentsponsor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournamentsponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('TITLE_SPONSOR', 'Title Sponsor'), ('CO_SPONSOR', 'Co-Sponsor'), ('PARTNER', 'Partner')], default='PARTNER', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsponsor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentsponsor',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_sponsorships', to='booking.sponsor'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsponsor',
            unique_together={('tournament', 'sponsor')},
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='company_details',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='sponsor_name',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='sponsorship_amount',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='sponsorship_type',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='updated_at',
        ),
    ]
